# Generated by Django 3.2.4 on 2021-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='hole_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
