# Generated by Django 3.2.4 on 2021-06-22 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_rounds', '0002_alter_golfround_hole_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfround',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='request_owner', to='users.user'),
            preserve_default=False,
        ),
    ]
